name: enough_mail_icalendar
description: iCalendar support for email / mime. Compatible with iCalendar Message-Based Interoperability Protocol (iMIP) RFC 6047.
version: 0.2.0
homepage: https://github.com/Enough-Software/enough_mail_icalendar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  enough_mail: #^1.3.6
    git:
      url: https://github.com/Enough-Software/enough_mail.git
    #path: ../enough_mail
  enough_icalendar: #'>=0.4.0 <= 2.0.0'
    git:
      url: https://github.com/Enough-Software/enough_icalendar.git
   #path: ../enough_icalendar

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
